[package]
name = "rs_command_line_worker"
version = "0.1.0"
authors = ["Valentin NOEL <valentin.noel@media-io.com>"]
edition = "2018"

[dependencies]
amqp_worker = { path = "../rs_amqp_worker" }
log = "0.4.5"
